### ISSUE TITLE
Join the org

### ISSUE THREAD

**Issue by VasudevJaiswal** [ankityadavhere/ankityadavhere#1]
[Click Here](https://github.com/Jaidevstudio/support/issues/new/choose)

**Comment by ankityadavhere** [comment]
Why? sir.

**Comment by VasudevJaiswal** [comment]
Check your email or org github pages

**Comment by VasudevJaiswal** [comment]
> Why? sir.

Working with Open-Source

**Comment by ankityadavhere** [comment]
Solomon, I don't want to.

**Comment by VasudevJaiswal** [comment]
Sorry for that

**Comment by ankityadavhere** [comment]
you still can close this, hmm hmm
